//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ScortelApi.Models.FLUX
{
    using System.Xml.Serialization;
 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:FLUXFAQueryMessage:3")]
    [System.Xml.Serialization.XmlRootAttribute("FLUXFAQueryMessage", Namespace = "urn:un:unece:uncefact:data:standard:FLUXFAQueryMessage:3", IsNullable = false)]
    public partial class FLUXFAQueryMessageType
    {

        private FAQueryType fAQueryField;

        /// <remarks/>
        public FAQueryType FAQuery
        {
            get
            {
                return this.fAQueryField;
            }
            set
            {
                this.fAQueryField = value;
            }
        }
    }


    
}
