using ScortelApi.Models.ScortelELB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ScortelApi.Models.Interfaces
{
    public interface IDIRec
    {
        int CompletionStatus { get; set; }
        string CompletionStatusStr { get; }
        byte Content { get; set; }
        DateTime CreationDT { get; set; }
        uint CreationDTL { get; set; }
        string CreationStatus { get; }
        string DIRecName { get; set; }
        DateTime DisRecCrDT { get; set; }
        List<FORec> FORecs { get; set; }
        byte FORecsCount { get; set; }
        long Id { get; set; }
        byte InsRecCount { get; set; }
        List<InsRec> InsRecs { get; set; }
        int SentStatus { get; set; }
        string SentStatusStr { get; }
        byte TransRecCount { get; set; }
        List<TransRec> TransRecs { get; set; }
        byte[] TripNumber { get; set; }
        string TripNumberStr { get; set; }

        void ExcludedInspRec();
        void ExcludeDisRecCrDTL();
        void ExcludedTransboardingRec();
        void ExcludeTripNumber();
        byte[] GetBytes(PosRec pos);
        void IncludeDisRecCrDTL();
        void IncludeInspRec();
        void IncludeTransbordingRec();
        void IncludeTripNuber();
        void SetAutoGenerated();
        void SetDataCorrection();
        void SetManualGenerated();
        void SetNoDataCorrection();
        void SetRandomTripNumber();
        void SetRealTripNumber();
    }
}
